/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const WorkItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : Time,
  'link' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'isVideo' : IDL.Bool,
  'orderIndex' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'socialLinks' : IDL.Vec(IDL.Text),
  'email' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addWorkItem' : IDL.Func(
      [
        IDL.Record({
          'title' : IDL.Text,
          'link' : IDL.Opt(IDL.Text),
          'description' : IDL.Text,
          'isVideo' : IDL.Bool,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteWorkItem' : IDL.Func([IDL.Nat], [], []),
  'getAllWorkItems' : IDL.Func([], [IDL.Vec(WorkItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoWorkItems' : IDL.Func([], [IDL.Vec(WorkItem)], ['query']),
  'getWorkItem' : IDL.Func([IDL.Nat], [IDL.Opt(WorkItem)], ['query']),
  'initialize' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOwner' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderWorkItems' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProfile' : IDL.Func([Profile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const WorkItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : Time,
    'link' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'isVideo' : IDL.Bool,
    'orderIndex' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'socialLinks' : IDL.Vec(IDL.Text),
    'email' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addWorkItem' : IDL.Func(
        [
          IDL.Record({
            'title' : IDL.Text,
            'link' : IDL.Opt(IDL.Text),
            'description' : IDL.Text,
            'isVideo' : IDL.Bool,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteWorkItem' : IDL.Func([IDL.Nat], [], []),
    'getAllWorkItems' : IDL.Func([], [IDL.Vec(WorkItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoWorkItems' : IDL.Func([], [IDL.Vec(WorkItem)], ['query']),
    'getWorkItem' : IDL.Func([IDL.Nat], [IDL.Opt(WorkItem)], ['query']),
    'initialize' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOwner' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderWorkItems' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProfile' : IDL.Func([Profile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };