/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Profile {
  'bio' : string,
  'displayName' : string,
  'socialLinks' : Array<string>,
  'email' : string,
  'phone' : [] | [string],
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkItem {
  'id' : bigint,
  'title' : string,
  'date' : Time,
  'link' : [] | [string],
  'description' : string,
  'isVideo' : boolean,
  'orderIndex' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addWorkItem' : ActorMethod<
    [
      {
        'title' : string,
        'link' : [] | [string],
        'description' : string,
        'isVideo' : boolean,
      },
    ],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteWorkItem' : ActorMethod<[bigint], undefined>,
  'getAllWorkItems' : ActorMethod<[], Array<WorkItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProfile' : ActorMethod<[], [] | [Profile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideoWorkItems' : ActorMethod<[], Array<WorkItem>>,
  'getWorkItem' : ActorMethod<[bigint], [] | [WorkItem]>,
  'initialize' : ActorMethod<[string, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOwner' : ActorMethod<[], boolean>,
  'reorderWorkItems' : ActorMethod<[Array<bigint>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProfile' : ActorMethod<[Profile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];